############ Environment ############
env: "cliffwalk"   # garnet / maze33 / cliffwalk
discount: 0.9

## cliffwalk
cliffwalk_success_prob: 0.9

############ Experiments ############

## Exp PE Exact
exp_pe_exact_num_iterations: 100
exp_pe_exact_alphas: [0, 0.1, 0.5, 0.8, 1]
exp_pe_exact_alphas_sensitivity: 0.02
exp_pe_exact_model_type: LocallySmoothed # LocallySmoothed, IdentitySmoothed

## Exp Control Exact
exp_control_exact_num_iterations: 25
exp_control_exact_alphas: [0, 0.1, 0.5, 0.8, 1]
exp_control_exact_alphas_sensitivity: 0.02
exp_control_exact_model_type: LocallySmoothed # LocallySmoothed, IdentitySmoothed
